[package]
name = "redis-rust-copy"
version = "0.1.0"
authors = ["iiibui <46981609+iiibui@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"